<?php


namespace Modules\User\Fortify;


use App\Helpers\ReCaptchaEngine;
use App\Rules\ValidCaptcha;

class LoginRequest extends \Laravel\Fortify\Http\Requests\LoginRequest
{

    public function rules()
    {
        $rules =  parent::rules(); // TODO: Change the autogenerated stub
        if (ReCaptchaEngine::isRequiredForAuth()) {
            $rules['g-recaptcha-response'] = ['required',new ValidCaptcha()];
        }

        return $rules;
    }

    public function messages()
    {
        return [
            'g-recaptcha-response.required'=>__('Please verify the captcha'),
        ];
    }
}
